apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: infraestructure
spec:
  releaseName: redis
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 21.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system